POST  http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
	"name":"Bob",
	"number":"555-564-5489"
}

###
GET http://localhost:3001 HTTP/1.1
###
GET http://localhost:3001/api/persons HTTP/1.1
###
GET http://localhost:3001/api/info HTTP/1.1
###
GET http://localhost:3001/api/persons/1 HTTP/1.1
###
GET http://localhost:3001/api/persons/20 HTTP/1.1
###
DELETE http://localhost:3001/api/persons/4 HTTP/1.1