PUT  http://localhost:3001/api/persons/5f6a0ff8dd3b744f7c3651c0 HTTP/1.1
Content-Type: application/json

{
	"number":"555-545-4657"
}
###
POST  http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
	"name":"Fred",
	"number":"555-654-8468"
}

###
GET http://localhost:3001 HTTP/1.1
###
GET http://localhost:3001/api/persons HTTP/1.1
###
GET http://localhost:3001/api/info HTTP/1.1
###
GET http://localhost:3001/api/persons/5f6a1344b16c294de49fb758 HTTP/1.1
###
GET http://localhost:3001/api/persons/20 HTTP/1.1
###
DELETE http://localhost:3001/api/persons/4 HTTP/1.1